version: "3.9"
services:
  notes_api:
    image: notes-api-image
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://notes_db:3306/notes_app
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - notes_db

  notes_db:
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: 12345678
        MYSQL_DATABASE: notes_app
    ports:
      - "3306:3306"
    volumes:
        - mysql-data-volume:/var/lib/mysql

volumes:
    mysql-data-volume:

